[project]
name = "optimal-leverage-constrained-portfolio"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10,<3.13"
dependencies = [
    "numpy>=2.2.2",
    "torch>=2.6.0",
]
